### ISSUE TITLE
SyntaxError when replace string icon name with a const

### ISSUE THREAD

**Issue by diegoleft** [javascripter/fontawesome.macro#23]
Hello guys, 
When I'm using a string like `fas('phone-alt')`  its works perfectly, but when I replace that string with a const or a props it giving me this error.

```error - ./components/layout/Molecules/ProductIconCard.js
SyntaxError: /components/layout/Molecules/ProductIconCard.js: fontawesome.macro: Invalid number or type of arguments.
  13 |   // }
  14 |   const icon = "phone-alt";
> 15 |   console.log("icon", fas(icon));
     |                       ^^^^^^^^^

```
What I'm doing wrong?

**Comment by javascripter** [comment]
Hi. This macro needs to receive string literals as the first argument to statically convert them to import statements at the moment (so that macros can converted into import statements at compile time).

Instead of storing names of icons to use in `fas` macros, you can store the values of `fas("phone-alt")` like below.
```javascript
const icon = fas("phone-alt");

<FontAwesome icon={icon} />
```

It may be possible to add support for some simple variables/constants that can be resolved to string literals at compile time, but cases like
```javascript
fas(Math.random() > 0.5 ? 'phone' : 'phone-alt')
```
are impossible to  be resolved as string literals at compile time so I think adding support for non-literals will be a bit confusing.
